// GENERATED by scripts/generate-migration-manifest.mjs -- do not edit.
//
// The migrations present in supabase/migrations at build time. The admin
// Settings screen compares this against applied_migrations() so that "in the
// repo" and "in the database" are the same question with one answer.

export type MigrationFile = {
  /** Numeric prefix. This is what the Supabase CLI records as the version. */
  version: string;
  name: string;
  file: string;
};

export const MIGRATION_MANIFEST: MigrationFile[] = [
  { version: '001', name: 'schema', file: '001_schema.sql' },
  { version: '002', name: 'rls', file: '002_rls.sql' },
  { version: '003', name: 'functions', file: '003_functions.sql' },
  { version: '004', name: 'grants', file: '004_grants.sql' },
  { version: '005', name: 'subcategories', file: '005_subcategories.sql' },
  { version: '006', name: 'subcategories_grants', file: '006_subcategories_grants.sql' },
  { version: '007', name: 'mixed_fulfilment', file: '007_mixed_fulfilment.sql' },
  { version: '008', name: 'checkout_functions', file: '008_checkout_functions.sql' },
  { version: '009', name: 'storefront_sorting', file: '009_storefront_sorting.sql' },
  { version: '010', name: 'store_settings', file: '010_store_settings.sql' },
  { version: '011', name: 'product_images', file: '011_product_images.sql' },
  { version: '012', name: 'scheduled_jobs', file: '012_scheduled_jobs.sql' },
  { version: '013', name: 'counter_orders', file: '013_counter_orders.sql' },
  { version: '014', name: 'grant_audit', file: '014_grant_audit.sql' },
  { version: '015', name: 'product_search', file: '015_product_search.sql' },
  { version: '016', name: 'migration_visibility', file: '016_migration_visibility.sql' },
  { version: '017', name: 'remove_demo_products', file: '017_remove_demo_products.sql' },
  { version: '018', name: 'product_condition', file: '018_product_condition.sql' },
  { version: '019', name: 'drop_adjusted_by_argument', file: '019_drop_adjusted_by_argument.sql' },
  { version: '020', name: 'reservation_order_fk_restrict', file: '020_reservation_order_fk_restrict.sql' },
  { version: '021', name: 'retire_parts_category', file: '021_retire_parts_category.sql' },
  { version: '022', name: 'admin_security', file: '022_admin_security.sql' },
  { version: '023', name: 'admin_policy_form', file: '023_admin_policy_form.sql' },
  { version: '024', name: 'admin_invites', file: '024_admin_invites.sql' },
  { version: '025', name: 'order_status_rules', file: '025_order_status_rules.sql' },
  { version: '026', name: 'product_archive', file: '026_product_archive.sql' },
  { version: '027', name: 'admin_invite_fix', file: '027_admin_invite_fix.sql' },
  { version: '028', name: 'checkout_integrity', file: '028_checkout_integrity.sql' },
  { version: '029', name: 'webhook_alerts', file: '029_webhook_alerts.sql' },
  { version: '030', name: 'notification_producer', file: '030_notification_producer.sql' },
  { version: '031', name: 'notification_extras', file: '031_notification_extras.sql' },
  { version: '032', name: 'service_role_grants', file: '032_service_role_grants.sql' },
  { version: '033', name: 'order_tracking', file: '033_order_tracking.sql' },
  { version: '034', name: 'customer_accounts', file: '034_customer_accounts.sql' },
  { version: '035', name: 'rate_limit', file: '035_rate_limit.sql' },
];
