// GENERATED by scripts/generate-migration-manifest.mjs -- do not edit.
//
// The migrations present in supabase/migrations at build time. The admin
// Settings screen compares this against applied_migrations() so that "in the
// repo" and "in the database" are the same question with one answer.

export type MigrationFile = {
  /** Numeric prefix. This is what the Supabase CLI records as the version. */
  version: string;
  name: string;
  file: string;
};

export const MIGRATION_MANIFEST: MigrationFile[] = [
  { version: '001', name: 'schema', file: '001_schema.sql' },
  { version: '002', name: 'rls', file: '002_rls.sql' },
  { version: '003', name: 'functions', file: '003_functions.sql' },
  { version: '004', name: 'grants', file: '004_grants.sql' },
  { version: '005', name: 'subcategories', file: '005_subcategories.sql' },
  { version: '006', name: 'subcategories_grants', file: '006_subcategories_grants.sql' },
  { version: '007', name: 'mixed_fulfilment', file: '007_mixed_fulfilment.sql' },
  { version: '008', name: 'checkout_functions', file: '008_checkout_functions.sql' },
  { version: '009', name: 'storefront_sorting', file: '009_storefront_sorting.sql' },
  { version: '010', name: 'store_settings', file: '010_store_settings.sql' },
  { version: '011', name: 'product_images', file: '011_product_images.sql' },
  { version: '012', name: 'scheduled_jobs', file: '012_scheduled_jobs.sql' },
  { version: '013', name: 'counter_orders', file: '013_counter_orders.sql' },
  { version: '014', name: 'grant_audit', file: '014_grant_audit.sql' },
  { version: '015', name: 'product_search', file: '015_product_search.sql' },
  { version: '016', name: 'migration_visibility', file: '016_migration_visibility.sql' },
];
